apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-hello
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-cluster
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-hello
  targetNamespace: default
  timeout: 3m0s
  wait: true
